config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "more"       => "pages#more"
  get "privacy"    => "pages#privacy"
  get "styleguide" => "pages#styleguide"
  get "up"         => "rails/health#show", as: :rails_health_check

  resource :session, only: %i[new create destroy]
  resources :password_resets, only: %i[new create edit update], param: :reset_token
  resources :users, only: %i[new create]

  resources :races, only: :show do
    scope module: :races do
      resource :replay, only: :show
    end
  end

  resources :recordings, only: [] do
    scope module: :recordings do
      resources :recorded_locations, only: :index
    end
  end

  namespace :my do
    resources :boats
    resources :memberships, only: %i[create destroy]
    resources :recordings, only: %i[index show edit update destroy] do
      scope module: :recordings do
        resources :recorded_locations, only: :index
        resource :speed_map, only: :show
      end
    end
  end

  namespace :admin do
    resources :boat_classes
    resource  :dashboard, only: :show
    resources :recordings, only: %i[index show destroy]
    resources :sailing_teams
    resources :users, only: %i[index show destroy]
    resources :yacht_clubs
  end

  namespace :api do
    namespace :v1 do
      post :login, to: "sessions#create"
      post :refresh, to: "sessions#refresh"
      delete :logout, to: "sessions#destroy"

      resources :boats
      resources :boat_classes, only: %i[index]
      resources :password_resets, only: %i[create update], param: :reset_token

      resources :races, only: %i[show] do
        scope module: :races do
          resources :course_marks, only: %i[index]
          resources :recordings, only: %i[index]
        end
      end

      resources :recordings do
        member do
          patch :end
        end

        scope module: :recordings do
          resource  :status, only: :show
          resources :maneuvers, only: :index
          resources :recorded_locations, only: %i[index create]
        end
      end

      namespace :users do
        get :email, to: "emails#show"
      end

      resources :users, only: [ :show, :create, :update, :destroy ]
    end
  end

  mount ActionCable.server => "/cable"
end

app/models/yacht_club.rb
class YachtClub < ApplicationRecord
  has_many :memberships, as: :organization, dependent: :destroy
  has_many :users, through: :memberships

  has_many :boats, as: :organization, dependent: :nullify

  has_one_attached :burgee

  validates :name, presence: true
end

app/controllers/admin/yacht_clubs_controller.rb
module Admin
  class YachtClubsController < BaseController
    before_action :set_yacht_club, only: %i[show edit update destroy]

    def index
      add_breadcrumb("Yacht clubs")
      @yacht_clubs = YachtClub.order(:name)
    end

    def show
      add_breadcrumb("Yacht clubs", admin_yacht_clubs_path)
      add_breadcrumb(@yacht_club.name)
    end

    def new
      add_breadcrumb("Yacht clubs", admin_yacht_clubs_path)
      add_breadcrumb("New")
      @yacht_club = YachtClub.new
    end

    def create
      @yacht_club = YachtClub.new(yacht_club_params)
      if @yacht_club.save
        redirect_to admin_yacht_club_path(@yacht_club), notice: "Yacht Club created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      add_breadcrumb("Yacht clubs", admin_yacht_clubs_path)
      add_breadcrumb(@yacht_club.name, admin_yacht_club_path(@yacht_club))
      add_breadcrumb("Edit")
    end

    def update
      if @yacht_club.update(yacht_club_params)
        redirect_to admin_yacht_club_path(@yacht_club), notice: "Yacht Club updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @yacht_club.destroy
      redirect_to admin_yacht_clubs_path, notice: "Yacht Club deleted."
    end

    private

    def set_yacht_club
      @yacht_club = YachtClub.find(params[:id])
    end

    def yacht_club_params
      params.require(:yacht_club).permit(
        :name,
        :abbreviation,
        :street_address,
        :city,
        :subdivision_code,
        :subdivision,
        :postal_code,
        :country_code,
        :country,
        :time_zone,
        :latitude,
        :longitude,
        :phone,
        :email,
        :is_active,
        :burgee
      )
    end
  end
end

app/views/admin/yacht_clubs/_form.html.erb
<%= sailtrace_form_for [:admin, yacht_club] do |f| %>
  <% if yacht_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(yacht_club.errors.count, "error") %> prevented this Yacht Club from being saved:</h2>
      <ul>
        <% yacht_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid grid-cols-1 gap-x-8 sm:grid-cols-6">
    <%= f.input :name,
                as: :text,
                label: "Name",
                wrapper_class: "sm:col-span-3",
                input_html: { title: "Enter the yacht club name", autofocus: !yacht_club.persisted?, autocomplete: :off, autocorrect: :off, required: true, spellcheck: false, autocapitalize: :words } %>

    <%= f.input :abbreviation,
                as: :text,
                label: "Abbreviation",
                wrapper_class: "sm:col-span-3",
                input_html: { title: "Enter the yacht club's abbreviation", autocomplete: :off, autocorrect: :off, required: true, spellcheck: false, autocapitalize: :characters } %>
  </div>

  <div class="grid grid-cols-1 gap-x-8 sm:grid-cols-6">
    <%= f.file_upload_input :burgee,
                            label: "Burgee",
                            wrapper_class: "sm:col-span-3",
                            hint: "PNG, JPG, SVG up to 10MB" %>

    <%= f.check_box_input :is_active,
                          label: "Active",
                          wrapper_class: "sm:col-span-3",
                          description: "Is this yacht club active on SailTrace?" %>
  </div>

  <div class="grid grid-cols-1 gap-x-8 sm:grid-cols-6">
    <%= f.input :street_address,
                as: :text,
                label: "Address",
                wrapper_class: "sm:col-span-6",
                input_html: { autocomplete: "street-address", autocorrect: :off, required: true, spellcheck: false, autocapitalize: :words } %>

    <%= f.input :city,
                as: :text,
                label: "City",
                wrapper_class: "sm:col-span-2",
                input_html: { autocomplete: "address-level2", autocorrect: :off, required: true, spellcheck: false, autocapitalize: :words } %>

    <%= f.input :subdivision,
                as: :text,
                label: "State",
                wrapper_class: "sm:col-span-2",
                input_html: { autocomplete: "address-level1", autocorrect: :off, required: true, spellcheck: false, autocapitalize: :characters, maxlength: 3 } %>

    <%= f.input :postal_code,
                as: :text,
                label: "Postal code",
                wrapper_class: "sm:col-span-2",
                input_html: { autocomplete: "postal-code", autocorrect: :off, required: true, spellcheck: false, autocapitalize: :characters } %>
  </div>

  <div class="grid grid-cols-1 gap-x-8 sm:grid-cols-6">
    <%= f.input :country,
                as: :select,
                label: "Country",
                collection: ISO3166::Country.pluck(:iso_short_name, :alpha2).sort_by { |data| data.first },
                priority_options: [["United States of America","US"]],
                wrapper_class: "sm:col-span-3",
                input_html: { title: "Select the country where this yacht club is located", autocomplete: :off, required: true } %>

    <%= f.input :time_zone,
                as: :select,
                label: "Time zone",
                collection: ActiveSupport::TimeZone.all.map { |tz| [tz.to_s, tz.tzinfo.identifier] },
                wrapper_class: "sm:col-span-3",
                input_html: { title: "Select the time zone where this yacht club is located", autocomplete: :off, required: true } %>

    <%= f.input :latitude,
                as: :number,
                label: "Latitude",
                wrapper_class: "sm:col-span-3",
                input_html: { autocomplete: :off, autocorrect: :off, spellcheck: false, step: :any } %>

    <%= f.input :longitude,
                as: :number,
                label: "Longitude",
                wrapper_class: "sm:col-span-3",
                input_html: { autocomplete: :off, autocorrect: :off, spellcheck: false, step: :any } %>
  </div>

  <div class="grid grid-cols-1 gap-x-8 sm:grid-cols-6">
    <%= f.input :email,
                as: :email,
                label: "Email address",
                wrapper_class: "sm:col-span-3",
                input_html: { autocomplete: :off, autocorrect: :off, required: true, autocapitalize: :off, spellcheck: false, title: "Enter the contact email address for the yacht club" } %>

    <%= f.input :phone,
                as: :tel,
                label: "Phone number",
                wrapper_class: "sm:col-span-3",
                input_html: { autocomplete: :off, autocorrect: :off, autocapitalize: :off, spellcheck: false, title: "Enter the primary phone number for the yacht club" } %>
  </div>

  <%= f.submit "Save",
               class: "mt-4 w-full inline-flex justify-center rounded-md bg-gray-900 dark:bg-white px-4 py-3 text-white dark:text-gray-950 hover:bg-gray-800 dark:hover:bg-white/95 cursor-pointer" %>
<% end %>

app/views/admin/yacht_clubs/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-10">
  <div class="mx-auto max-w-3xl">
    <h1 class="text-2xl/8 font-semibold text-gray-950 sm:text-xl/8 dark:text-white mb-10">Update yacht club</h1>
    <%= render "form", yacht_club: @yacht_club %>
    <p class="mt-10">
      <%= link_to "View this yacht club", admin_yacht_club_path(@yacht_club) %> |
      <%= link_to "Back to yacht clubs", admin_yacht_clubs_path %>
    </p>
  </div>
</div>

app/views/admin/yacht_clubs/index.html.erb
<div class="container">
  <h1 class="text-xx-large text-bold">Yacht Clubs</h1>

  <div class="margin-block">
    <% @yacht_clubs.each do |club| %>
      <%= link_to admin_yacht_club_path(club), class: "panel margin-block flex" do %>
        <div>
          <p class="text-small text-muted margin-block-end-half">
            <%= club.abbreviation %>
          </p>
          <p><%= club.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= link_to "New Yacht Club", new_admin_yacht_club_path, class: "btn btn--reversed" %>
</div>

app/views/admin/yacht_clubs/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-10">
  <div class="mx-auto max-w-3xl">
    <h1 class="text-2xl/8 font-semibold text-gray-950 sm:text-xl/8 dark:text-white mb-10">New yacht club</h1>
    <%= render "form", yacht_club: @yacht_club %>
    <p class="mt-10">
      <%= link_to "Back to yacht clubs", admin_yacht_clubs_path %>
    </p>
  </div>
</div>

app/views/admin/yacht_clubs/show.html.erb
<div class="container">
  <h1 class="text-xx-large text-bold"><%= @yacht_club.name %></h1>

  <% if @yacht_club.burgee.attached? %>
    <%= image_tag @yacht_club.burgee, class: "border block my-4", alt: "#{@yacht_club.name} Burgee" %>
  <% end %>

  <p><strong>City:</strong> <%= @yacht_club.city %></p>
  <p><strong>Phone:</strong> <%= @yacht_club.phone %></p>
  <p><strong>Email:</strong> <%= @yacht_club.email %></p>

  <div class="flex gap margin-block">
    <%= link_to "Edit", edit_admin_yacht_club_path(@yacht_club), class: "btn" %>
    <%= button_to "Delete", admin_yacht_club_path(@yacht_club),
        method: :delete,
        data: { turbo_confirm: "Are you sure?" },
        class: "btn" %>
  </div>
</div>